# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fa', '0002_archive_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CommaSeparatedIntegerField(blank=True, max_length=255, null=True)),
                ('archives', models.ManyToManyField(blank=True, to='fa.Archive')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Findingaids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_publish', 'Can publish a finding aid'), ('can_preview', 'Can preview a finding aid'), ('can_delete', 'Can delete a finding aid'), ('can_prepare', 'Can prepare a finding aid'), ('can_view_internal_dao', 'Can view internal digital archival objects')),
            },
        ),
    ]
