
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~  FOOTER  ~~~~~~~~~~~~~~~~~~~~~~~ -->

<div class="footer">
  <hr/>
	<p>&copy; Emory University, Manuscript, Archives, and Rare Book Library<br>
     For more information please contact: <a href="mailto:MARBL@emory.edu">MARBL@emory.edu</a>.
  </p>
</div>	

<!--BEGIN Google Analytics Script for MARBL -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4588980-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<!--END Google Analytics Script for MARBL -->


	
</body>
<!-- InstanceEnd --></html>
