<?
include_once("common_functions.php");

$baseURL  = "http://marbl.library.emory.edu";

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
	<html xmlns="http://www.w3.org/1999/xhtml">

  <!-- InstanceBegin template="/templates/sub_woodruff.dwt" codeOutsideHTMLIsLocked="false" -->

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<!-- <link href="<?= $baseURL ?>/includes/css/main.css" rel="stylesheet" type="text/css" />
<link href="<?= $baseURL ?>/includes/css/web.css" rel="stylesheet" type="text/css" /> -->
<link href="css/marblfa.css" rel="stylesheet" type="text/css" />

<script src="<?= $baseURL ?>/includes/js/common.js" type="text/javascript" language="javascript"></script>
<!-- InstanceBeginEditable name="doctitle" -->
<!-- InstanceEndEditable -->


<!-- InstanceParam name="show_leftnav" type="boolean" value="true" -->
<!-- InstanceParam name="show_toolBar" type="boolean" value="true" -->
<!-- InstanceBeginEditable name="head" -->
<!-- InstanceEndEditable -->







</head>

<body bottommargin="0" leftmargin="4" marginheight="4" marginwidth="4" rightmargin="4" topmargin="4" bgcolor="#cccc99">

<div class="header">
  
  <div id="emory" class="logo">
    <a href="http://marbl.library.emory.edu"><img src="images/emory.png"/></a>
  </div>

  <div id="boston" class="logo">
    <a href="http://marbl.library.emory.edu"><img src="images/boston.png"/></a>
  </div>

  <div id="sitetitle">
    <a href="index.php">Irish Literary Collections Portal</a>
  </div>


  <div id="nav">
    <a href="doc.php?id=generalinfo">General Information</a>
    <a href="rqst.php">Search</a>
    <a href="browse.php">The Collections</a>
    <a href="doc.php?id=resources">Other Resources</a>
  </div>


</div>

	
  

