<!-- #BeginLibraryItem "/Library/marbl_toolbar.lbi" -->
<!-- ~~~~~~~~~~~~~~~~~~~~~~~  MARBL Toolbar  ~~~~~~~~~~~~~~~~~~~~~~~ -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tbody><tr align="center" bgcolor="#d5d9e5" height="25">
    <td>&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://www.library.emory.edu/">EUCLID</a></td>

    <td><a href="http://irishliterature.library.emory.edu/">Irish Literary Collections Portal </a></td>
    <td><a href="<?= $baseURL ?>/Guides/">MARBL Subject Guides</a></td>
    <td><a href="<?= $baseURL ?>/Finding/Descriptions/digitized.html">Digital Collections</a></td>
  </tr>
</tbody></table>
<!-- #EndLibraryItem --><br>