		</td>
		<td valign="top" width="5" background="<?= $baseURL ?>/images/common/shadow_right_bg.gif"><img src="<?= $baseURL ?>/images/subpage/sub_shadow_right.gif" width="5" height="225" alt=""></td>
	</tr>

	<!-- ~~~~~~~~~~~~~~~~~~~~~~~  FOOTER  ~~~~~~~~~~~~~~~~~~~~~~~ -->
	<tr>
		<td colspan="3" background="<?= $baseURL ?>/images/subpage/subfooter_bg.gif">
			<table border="0" cellpadding="0" cellspacing="0" width="100%">
				<tr>
					<td align="left"><img src="<?= $baseURL ?>/images/subpage/subfooter_1.gif" width="619" height="10" alt=""></td>
					<td align="right"><img src="<?= $baseURL ?>/images/subpage/subfooter_2.gif" width="87" height="10" alt=""></td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<img src="<?= $baseURL ?>/images/common/spacer.gif" width="1" height="4" alt="">

<!-- ~~~~~~~~~~~~~~~~~~~~~~~  IMAGE MAP HOT SPOTS ON LOGO ROW ~~~~~~~~~~~~~~~~~~~~~~~ -->
<map name="_stretch">
<area alt="" coords="352,1,450,14" href="http://www.emory.edu/">
<area alt="" coords="225,103,339,115" href="http://web.library.emory.edu/using/myaccount/">
<area alt="" coords="344,104,450,117" href="http://www.library.emory.edu/uhtbin/nph-illiad">
</map>

</body>
<!-- InstanceEnd --></html>
