
</div>
			<!-- end rightColWide -->
		
		</div>
		<!-- end interiorContainer -->
	
<!-- begin footer --><!-- #BeginLibraryItem "/Library/footer.lbi" -->
        <div id="footer">
	        <div id="footerNav">
        <a href="<?= $baseURL ?>/index.html" title="Home">Home</a> | <a href="<?= $baseURL ?>/support-marbl.html" title="Support MARBL">Support MARBL</a> | <a href="<?= $baseURL ?>/contact-marbl.html" title="Contact MARBL">Contact MARBL</a><br />
        <a href="http://web.library.emory.edu" title="Main Library Website">Main Library Website</a> | <a href="http://www.emory.edu" title="Emory University Website">Emory University Website</a> | <a href="http://www.library.emory.edu" title="Emory Libraries Catalog">Emory Libraries Catalog</a>
    	    </div>
        	<div id="footerInfo">
        Manuscript, Archives, and Rare Book Library<br />
        Robert W. Woodruff Library, Emory University, Atlanta, GA 30322-2870<br />
        email: <a title="Email MARBL" href="mailto:marbl@emory.edu">marbl@emory.edu</a> phone: 404.727.6887 fax: 404.727.0360<br />
        	</div>
        </div>
        <div id="footerShadow"></div>

<!--BEGIN Google Analytics Script for MARBL -->
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-4588980-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
<!-- #EndLibraryItem --><!-- end footer -->

</div>
	<!-- /end container -->         

</body>
</html>
